### ISSUE TITLE
Simpler?

### ISSUE THREAD

**Issue by solsend2l** [mathiasbynens/String.prototype.includes#4]
Curious, what do you see is the problem with this polyfill?

```js
if (!String.prototype.includes) {
  String.prototype.includes = function() {'use strict';
    return String.prototype.indexOf.apply(this, arguments) !== -1;
  };
}
```

[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

**Comment by mathiasbynens** [comment]
Try running it against [the tests](https://raw.githubusercontent.com/mathiasbynens/String.prototype.includes/master/tests/tests.js) and you’ll see :)
